/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin-announcements'
import { Route as AdminAuditLogRouteImport } from './routes/admin-audit-log'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminPlayersRouteImport } from './routes/admin-players'
import { Route as AdminTeamsRouteImport } from './routes/admin-teams'
import { Route as AdminTournamentsRouteImport } from './routes/admin-tournaments'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as RefereeRouteImport } from './routes/referee'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterTeamRouteImport } from './routes/register-team'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TournamentsRouteImport } from './routes/tournaments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin-announcements',
  path: '/admin-announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin-audit-log',
  path: '/admin-audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/admin-players',
  path: '/admin-players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin-teams',
  path: '/admin-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin-tournaments',
  path: '/admin-tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeRoute = RefereeRouteImport.update({
  id: '/referee',
  path: '/referee',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTeamRoute = RegisterTeamRouteImport.update({
  id: '/register-team',
  path: '/register-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
  '/tickets': typeof TicketsRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
  '/tickets': typeof TicketsRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-announcements': typeof AdminAnnouncementsRoute
  '/admin-audit-log': typeof AdminAuditLogRoute
  '/admin-login': typeof AdminLoginRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/admin-users': typeof AdminUsersRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
  '/tickets': typeof TicketsRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-announcements'
    | '/admin-audit-log'
    | '/admin-login'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/admin-users'
    | '/login'
    | '/matches'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
    | '/tickets'
    | '/tournaments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-announcements'
    | '/admin-audit-log'
    | '/admin-login'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/admin-users'
    | '/login'
    | '/matches'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
    | '/tickets'
    | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-announcements'
    | '/admin-audit-log'
    | '/admin-login'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/admin-users'
    | '/login'
    | '/matches'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
    | '/tickets'
    | '/tournaments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  RefereeRoute: typeof RefereeRoute
  RegisterRoute: typeof RegisterRoute
  RegisterTeamRoute: typeof RegisterTeamRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TicketsRoute: typeof TicketsRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-announcements': {
      id: '/admin-announcements'
      path: '/admin-announcements'
      fullPath: '/admin-announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-audit-log': {
      id: '/admin-audit-log'
      path: '/admin-audit-log'
      fullPath: '/admin-audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-players': {
      id: '/admin-players'
      path: '/admin-players'
      fullPath: '/admin-players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-teams': {
      id: '/admin-teams'
      path: '/admin-teams'
      fullPath: '/admin-teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tournaments': {
      id: '/admin-tournaments'
      path: '/admin-tournaments'
      fullPath: '/admin-tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee': {
      id: '/referee'
      path: '/referee'
      fullPath: '/referee'
      preLoaderRoute: typeof RefereeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-team': {
      id: '/register-team'
      path: '/register-team'
      fullPath: '/register-team'
      preLoaderRoute: typeof RegisterTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  RefereeRoute: RefereeRoute,
  RegisterRoute: RegisterRoute,
  RegisterTeamRoute: RegisterTeamRoute,
  ScoreboardRoute: ScoreboardRoute,
  TicketsRoute: TicketsRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
