/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminPlayersRouteImport } from './routes/admin-players'
import { Route as AdminTeamsRouteImport } from './routes/admin-teams'
import { Route as AdminTournamentsRouteImport } from './routes/admin-tournaments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RefereeRouteImport } from './routes/referee'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegisterTeamRouteImport } from './routes/register-team'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/admin-players',
  path: '/admin-players',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin-teams',
  path: '/admin-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin-tournaments',
  path: '/admin-tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeRoute = RefereeRouteImport.update({
  id: '/referee',
  path: '/referee',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTeamRoute = RegisterTeamRouteImport.update({
  id: '/register-team',
  path: '/register-team',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/login': typeof LoginRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/login': typeof LoginRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-players': typeof AdminPlayersRoute
  '/admin-teams': typeof AdminTeamsRoute
  '/admin-tournaments': typeof AdminTournamentsRoute
  '/login': typeof LoginRoute
  '/referee': typeof RefereeRoute
  '/register': typeof RegisterRoute
  '/register-team': typeof RegisterTeamRoute
  '/scoreboard': typeof ScoreboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/login'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/login'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-players'
    | '/admin-teams'
    | '/admin-tournaments'
    | '/login'
    | '/referee'
    | '/register'
    | '/register-team'
    | '/scoreboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  LoginRoute: typeof LoginRoute
  RefereeRoute: typeof RefereeRoute
  RegisterRoute: typeof RegisterRoute
  RegisterTeamRoute: typeof RegisterTeamRoute
  ScoreboardRoute: typeof ScoreboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-players': {
      id: '/admin-players'
      path: '/admin-players'
      fullPath: '/admin-players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-teams': {
      id: '/admin-teams'
      path: '/admin-teams'
      fullPath: '/admin-teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tournaments': {
      id: '/admin-tournaments'
      path: '/admin-tournaments'
      fullPath: '/admin-tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee': {
      id: '/referee'
      path: '/referee'
      fullPath: '/referee'
      preLoaderRoute: typeof RefereeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-team': {
      id: '/register-team'
      path: '/register-team'
      fullPath: '/register-team'
      preLoaderRoute: typeof RegisterTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  LoginRoute: LoginRoute,
  RefereeRoute: RefereeRoute,
  RegisterRoute: RegisterRoute,
  RegisterTeamRoute: RegisterTeamRoute,
  ScoreboardRoute: ScoreboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
